### ISSUE TITLE
where should I put the pre-translated SRT file or what do I do wrong with something else

### ISSUE THREAD

**Issue by benshgit** [ThioJoe/Auto-Synced-Translated-Dubs#58]
I put the pre-translated SRT file in the directory same as main.py, and also copy it into workingfolder. Then it gives me the following message:
------- 'Auto Synced Translated Dubs' script by ThioJoe - Release version 0.13.1 -------

----- Beginning Processing of Languages -----

----- Beginning Processing of Language (1/1): zh-CN -----
Skip translation enabled. Checking for pre-translated subtitles...
Pre-translated subtitles not found for language: zh-CN. Skipping.

**Comment by ThioJoe** [comment]
It would go into the same output folder that the script would output the subtitles or audio files.

So if the video file is called `Some Video.mp4`, you would put the subtitle files into: `Outputs\Some Video`

Keep in mind it will be looking for a certain format for the name of the srt file, specifically ending with the two letter language code. In your case it should end with ` - zh.srt`. This is because it is assuming the file was created by the script. So the whole filename would be `whatever file name - zh.srt`

I'll probably have to add some kind of messaging to make this a bit more obvious
