### ISSUE TITLE
Support for .vtt subtitle files?

### ISSUE THREAD

**Issue by leonimurilo** [ThioJoe/Auto-Synced-Translated-Dubs#88]
I really appreciate this project, and I am considering using it for some projects. My project uses .vtt files instead of .srt files.

I didn't see anything mentioning support for .vtt files. Converting from one to another is not an option I wanna go with because I would lose some information after the conversion.

I wonder if this project supports .vtt files out of the box. If not, how much effort would it require to add this functionality? I mean, is the code highly coupled with .srt files or is it easy to plug-in some kind of adapter for vtt?

**Comment by ThioJoe** [comment]
It doesn't support VTT at the moment. I am not really familiar with how VTT is formatted, but after a quick search it seems to support a lot more formatting and metadata. The way the script works might make it hard to support VTT, because right now the script basically combines subtitle lines together to try and optimize for the text-to-speech synthesis of the lines. So I'm not sure how I'd be able to handle combining lines that have different metadata for example. So at the moment I don't think I can plan on adding VTT support any time soon.

**Comment by leonimurilo** [comment]
No problem. Thank you very much for the quick reply.

I will evaluate the needs of my project and if I really need .vtt support and if we do, then maybe my team can collaborate with this project.
